name: Deploy to EC2

on:
  push:
    branches:
      - main # Changer si vous utilisez une autre branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }} # Remplacez par l'adresse IP de votre instance EC2
        username: ${{ secrets.EC2_USERNAME }} # Votre nom d'utilisateur EC2
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Votre clé privée SSH (stockée dans les secrets GitHub)
        script: |
          cd
          cd gaia-back/Infra-2.0-Back/
          git pull origin main
          npm install
          node app.js

